### ISSUE TITLE
Get text to float around pictures for interns

### ISSUE THREAD

**Issue by EvanMisshula** [cisdd/incsite#6]

**Comment by KevinRamsunder** [comment]
I've been looking at this for a while now, and here is my two cents.

I believe we need to add the CSS theme we are working with to the repo so we all can generate the website based on the same settings. For example, if I generate the website based on my own local modified theme, the changes will be lost when any of you try to generate the website. 

I have my own copy of the 'NotMyIdea' theme from here: https://github.com/getpelican/pelican-themes/tree/master/notmyidea-cms, and there are more here: https://github.com/getpelican/pelican-themes. 

Currently, the pelicanconf.py file, https://github.com/cisdd/incsite/blob/master/pelicanconf.py, selects the theme in this directory: '/home/evan/pelican-themes/tuxlite_tbs'. So maybe we can add this theme to the repo for collaboration?

**Comment by MatthewBlanco** [comment]
So I have actually been doing work on this.  You all can see the progress I have made on my fork of this site.

github.com/MatthewBlanco/incsite <http://github.com/MatthewBlanco/incsite>

I have put in a few pull requests and am just waiting on approval


----
Matthew Blanco
(516) 728 - 5045

**Comment by KevinRamsunder** [comment]
Nice, I've been doing the same.

I see that you have added the themes you are working on to your fork, which addresses my concerns above. 

Thanks.

**Comment by MatthewBlanco** [comment]
Awesome, this wasn't to say that you shouldn't also be working on it.  I just didn't want us to have done the same things, or even worse conflicting things.

**Comment by EvanMisshula** [comment]
I have included a theme folder.  The other way to do this is used the themes installed in the Virtual Environment.  I needed to delete the 'built in' themes by hand.
